game.add_item_to_group( "pawn", "nec_ball_chain", 3 )
game.add_item_to_group( "pawn", "nec_fine_katana", 1 )
game.add_item_to_group( "art", "nec_fine_katana", 1 )
game.add_item_to_group( "weapons", "nec_fine_katana", 1 )
game.add_item_to_group( "weapons", "nec_ball_chain", 3 )
game.add_item_to_group( "weapons", "nec_assasin_blade", 2 )
game.add_item_to_group( "antique_rare", "nec_fine_katana", 2 )
game.add_item_to_group( "antique_rare", "nec_assasin_blade", 2)
game.add_item_to_group( "museum_melee", "nec_fine_katana", 1)
game.add_item_to_group( "museum_melee", "nec_ball_chain", 3)
game.add_item_to_group( "museum_melee", "nec_assasin_blade", 2)
game.add_item_to_group( "medieval", "nec_ball_chain", 10)
game.add_item_to_group( "medieval", "nec_assasin_blade", 2)
game.add_item_to_group( "survivorzed_extra", "nec_jogiri", 10)
game.add_item_to_group( "prison_weapons", "nec_ball_chain" 10)
