game.add_item_to_group( "cop_evidence", "ug_cashcard_reader", 2 )
game.add_item_to_group( "npc_hacker", "ug_cashcard_reader", 5 )
game.add_item_to_group( "rare", "ug_cashcard_reader", 5 )
game.add_item_to_group( "magazines", "hacker_manifesto", 3)
game.add_item_to_group( "elecsto_books", "hacker_manifesto", 5)
game.add_item_to_group( "electronics", "hacker_manifesto", 5)
game.add_item_to_group( "NC_HACKER_misc", "hacker_manifesto" 4)
game.add_item_to_group( "pawn", "nec_ball_chain", 3 )
game.add_item_to_group( "pawn", "nec_fine_katana", 1 )
game.add_item_to_group( "art", "nec_fine_katana", 1 )
game.add_item_to_group( "weapons", "nec_fine_katana", 1 )
game.add_item_to_group( "weapons", "nec_ball_chain", 3 )
game.add_item_to_group( "weapons", "nec_assasin_blade", 2 )
game.add_item_to_group( "antique_rare", "nec_fine_katana", 2 )
game.add_item_to_group( "antique_rare", "nec_assasin_blade", 2)
game.add_item_to_group( "museum_melee", "nec_fine_katana", 1)
game.add_item_to_group( "museum_melee", "nec_ball_chain", 3)
game.add_item_to_group( "museum_melee", "nec_assasin_blade", 2)
game.add_item_to_group( "medieval", "nec_ball_chain", 10)
game.add_item_to_group( "medieval", "nec_assasin_blade", 2)
game.add_item_to_group( "survivorzed_extra", "nec_jogiri", 10)
game.add_item_to_group( "prison_weapons", "nec_ball_chain" 10)
game.add_item_to_group( "toy_store", "power_glove_box", 10)
game.add_item_to_group( "elecsto_persele", "power_glove_box", 35)
game.add_item_to_group( "livingroom", "power_glove_box", 3)
game.add_item_to_group( "pawn", "power_glove_box", 3)
game.add_item_to_group( "cop_evidence", "hack_watch_adv", 2)
game.add_item_to_group( "school", "software_math", 10)
game.add_item_to_group( "default_zombie_death_drops", "software_math", 1)
game.add_item_to_group( "default_zombie_death_drops", "software_hacking", 1)